### ISSUE TITLE
typo (maybe)

### ISSUE THREAD

**Issue by sandgate-dev** [learn-co-curriculum/dsc-3-31-02-introduction-to-PAC-learning-theory#1]
You write:

> PAC uses the term 'hypothesis',whereas ML literature normally uses the term 'model'. So we have seen that Machine learning starts with some data, (xi,yi) and we want to find a hypothesis (or mode) that will, given the inputs ...

_(to mode)_ should read as **_(to model)_**

**Comment by fpolchow** [comment]
corrected typo
